# One Good Trade Per Day Bot Configuration
# 🎯 Edit these settings - NO code changes needed

# EXCHANGE SETTINGS
exchange:
  name: "kraken"   # kraken, binance, coinbase (using kraken for live data)
  sandbox: false   # Use live Kraken data (no sandbox available)
  api_key: ""      # Your API key (not needed for market data)
  secret: ""       # Your API secret (not needed for market data)
  
# TRADING PARAMETERS  
trading:
  account_balance: 10000    # Starting capital in USD
  max_risk_per_trade: 0.01  # 1% risk per trade (0.01 = 1%)
  max_position_pct: 0.10    # Max 10% of account per position
  max_spread_pct: 0.003     # Max 0.3% bid-ask spread
  max_positions: 1          # Only ONE position at a time
  
# WATCHLIST - Focus on liquid, trending assets
watchlist:
  - "BTC/USD"
  - "ETH/USD"  
  - "SOL/USD"
  - "AVAX/USD"
  - "HBAR/USD"

# FILTER SETTINGS
filters:
  # Filter 1: Market Regime
  regime:
    min_trend_distance: 0.02    # 2% from SMA20 to be "trending"
    max_atr_pct: 0.08           # 8% max ATR/price ratio
    min_volume_ratio: 0.5       # 50% of 20-day average volume
    max_bb_squeeze: 0.15        # Max BB squeeze threshold
    min_checks_pass: 3          # Must pass 3/4 regime checks
    
  # Filter 2: Setup Scanner  
  setup:
    min_setup_score: 60         # Minimum 60/100 setup score
    rsi_oversold_min: 30        # RSI must be >= 30
    rsi_oversold_max: 45        # RSI must be <= 45
    sma20_tolerance: 0.02       # Within 2% of SMA20 for pullback
    volume_increase_min: 1.1    # 110% recent volume vs average
    
  # Filter 3: Confluence
  confluence:
    min_confluence_score: 50    # Minimum 50/80 confluence score
    min_risk_reward: 2.0        # Minimum 2:1 risk:reward ratio
    fib_tolerance: 0.015        # Within 1.5% of fib level
    volume_profile_strength: 1.5 # 150% volume at current level
    
  # Filter 4: Risk Check
  risk:
    max_stop_distance_pct: 0.05 # Max 5% stop loss distance
    min_liquidity_ratio: 0.0005 # Max 0.05% of daily volume
    news_avoidance_hours: 4     # Avoid trades 4h before events

# EXECUTION SETTINGS - HYBRID APPROACH
execution:
  entry_timeout_hours: 6      # Daily target expires after 6 hours
  monitor_interval: 5         # Check entry conditions every 5 minutes
  order_type: "limit"         # Always use limit orders
  slippage_tolerance: 0.001   # 0.1% slippage tolerance
  entry_zone_tolerance: 0.005 # 0.5% tolerance around ideal entry
  order_fill_timeout: 30      # Cancel unfilled orders after 30 minutes

# TIMING
schedule:
  scan_time: "08:00"          # UTC time for daily scan
  timezone: "UTC"
  
# LOGGING
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  log_trades: true
  log_scans: true
  log_vetoes: true
  
# DATABASE  
database:
  path: "trades.db"
  backup_days: 90             # Keep 90 days of history

# PAPER TRADING SETTINGS - ALIGNED WITH CORE PRINCIPLES
paper_trading:
  initial_balance: 10000      # Starting virtual balance ($)
  position_size_pct: 0.01     # 1% risk per trade (MATCHES MAIN CONFIG)
  trading_fees: 0.001         # 0.1% trading fees
  slippage: 0.0005           # 0.05% slippage simulation
  max_positions: 1            # ONE POSITION RULE (CORE PRINCIPLE)
  check_interval: 1440        # Check once per day (1440 minutes = 24 hours)
  risk_per_trade: 0.01       # 1% account risk per trade (DISCIPLINE)
  stop_loss_pct: 0.02        # 2% stop loss
  take_profit_pct: 0.04      # 4% take profit (2:1 R:R)
  close_on_exit: false       # Keep positions open on session end
  
  # Enhanced features
  use_live_market_data: true  # Use CCXT for real market data (Kraken live data!)
  use_bid_ask_simulation: true # Simulate bid/ask spreads for realistic fills
  order_timeout_hours: 4      # Cancel orders after X hours
  database_path: "paper_trading.db"  # SQLite database for trade journaling